import mongoose from 'mongoose';

const { Schema } = mongoose;

const meituanOrdersSchema = new Schema({
  orderId: Number,
  orderTime: Number,
  ctime: Number,
  mtime: Number,
  recipientAddress: String,
  recipientName: String,
  recipientPhone: String,
  addressLongitude: Number,
  addressLatitude: Number,
  cityId: Number,
  shippingFee: Number,
  nightShippingFee: Number,
  estimateArrivalTime: Number,
  caution: String,
  needInvoice: Boolean,
  invoiceTitle: String,
  invoiceTaxpayerId: String,
  orderPayType: Number,
  orderPayStatus: Number,
  restaurantId: {
    type: Schema.ObjectId,
    ref: 'MeituanRestaurants',
  },
  restaurantName: String,
  restaurantMinFee: Number,
  total: Number,
  originalPrice: Number,
  boxTotalPrice: Number,
  userId: Number,
  userPhone: String,
  isPreOrder: Boolean,
  isFirstOrder: Boolean,
  deliveryType: Boolean,
  discountWarnTip: String,
  token: String,
  payUrl: String,
  statusId: Number,
  remark: String,
  courierName: String,
  courierPhone: String,
  courierAvatar: String,
  courierLongitude: Number,
  courierLatitude: Number,
  channel: String,
  logisticsStatus: Number,
  orderingDetail: [{
    productId: {
      type: Schema.ObjectId,
      ref: 'MeituanProducts',
    },
    skuId: Number,
    foodPrice: Number,
    unit: String,
    count: Number,
    boxNum: Number,
    boxPrice: Number,
    foodName: String,
    originFoodPrice: Number,
    picture: String,
    spec: String,
    spuAttr: [{
      id: Number,
      spuId: Number,
      no: Number,
      name: String,
      value: String,
      valid: Number,
    }],
  }],
  orderingUnavailable: [{
    skuId: Number,
    foodName: String,
    stock: Number,
    productId: {
      type: Schema.ObjectId,
      ref: 'MeituanProducts',
    },
  }],
  minCountFood: [{
    skuId: Number,
    foodName: String,
    productId: {
      type: Schema.ObjectId,
      ref: 'MeituanProducts',
    },
    curCount: Number,
    minCount: Number,
  }],
  discounts: [{
    name: String,
    info: String,
    reduceFee: String,
    iconUrl: String,
  }],
  createTime: {
    type: Date,
    default: new Date(),
  },
});

const MeituanOrders = mongoose.model('Order', meituanOrdersSchema);
export default MeituanOrders;
